"use strict";

const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");
const esbuild = require("esbuild");

const ROOT = path.resolve(__dirname, "..");

// Keep the generated icon catalog in sync with the bundled glyph subset before
// bundling, so the picker can never offer an icon the firmware lacks.
require("node:child_process").execFileSync(
  process.execPath, [path.join(__dirname, "build_icon_catalog.js")],
  { stdio: "inherit" },
);

function toByteArrayLines(buffer) {
  let out = "";
  for (let offset = 0; offset < buffer.length; offset += 20) {
    const chunk = [];
    for (let i = offset; i < Math.min(offset + 20, buffer.length); i += 1) {
      chunk.push(buffer[i].toString());
    }
    out += "  " + chunk.join(",") + ",\n";
  }
  return out;
}

const result = esbuild.buildSync({
  absWorkingDir: ROOT,
  entryPoints: ["web/index.ts"],
  bundle: true,
  format: "iife",
  minify: true,
  target: "es2020",
  write: false,
});
if (result.outputFiles.length !== 1) throw new Error("unexpected esbuild output");

const js = Buffer.from(result.outputFiles[0].text, "utf-8");
const jsGz = zlib.gzipSync(js, { level: 9 });
const html = fs.readFileSync(path.join(ROOT, "web/index.html"));

const header =
  "#pragma once\n" +
  "#include <cstddef>\n" +
  "#include <cstdint>\n\n" +
  "// GENERATED by scripts/build_deck_ui.js — do not edit by hand.\n" +
  "namespace poc {\n\n" +
  "inline const uint8_t kDeckUiHtml[] = {\n" + toByteArrayLines(html) + "};\n" +
  "inline constexpr size_t kDeckUiHtmlLen = sizeof(kDeckUiHtml);\n\n" +
  "inline const uint8_t kDeckUiAppJsGz[] = {\n" + toByteArrayLines(jsGz) + "};\n" +
  "inline constexpr size_t kDeckUiAppJsGzLen = sizeof(kDeckUiAppJsGz);\n\n" +
  "}  // namespace poc\n";

const outPath = path.join(ROOT, "firmware/native/deck_ui_asset.h");
fs.writeFileSync(outPath, header);
console.log(`wrote ${outPath}: html=${html.length}B js=${js.length}B js.gz=${jsGz.length}B`);
