"use strict";

// Generates web/icon_catalog.ts from firmware/assets/icon_glyphs.yaml.
// The firmware bundles exactly this subset of MDI glyphs, so the configurator's
// icon picker offers exactly these (anything else renders blank on the device).
//
//   node scripts/build_icon_catalog.js          # write the file
//   node scripts/build_icon_catalog.js --check   # exit 1 if it would change

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "firmware/assets/icon_glyphs.yaml");
const OUT = path.join(ROOT, "web/icon_catalog.ts");

// Each glyph line looks like:  - "\U000F0493"  # mdi-cog (Auto fallback)
const LINE = /^\s*-\s*"\\U([0-9A-Fa-f]{8})"\s*#\s*mdi-([a-z0-9-]+)/;

function parseCatalog(text) {
  const seenGlyph = new Set();
  const seenSlug = new Set();
  const entries = [];
  for (const raw of text.split(/\r?\n/)) {
    const m = LINE.exec(raw);
    if (!m) continue;
    const codeHex = m[1].toUpperCase().replace(/^0+(?=.)/, "");
    const slug = m[2];
    const glyph = String.fromCodePoint(Number.parseInt(m[1], 16));
    if (seenGlyph.has(glyph) || seenSlug.has(slug)) continue;
    seenGlyph.add(glyph);
    seenSlug.add(slug);
    entries.push({ name: slug.replace(/-/g, " "), slug, hex: codeHex, glyph });
  }
  entries.sort((a, b) => a.slug.localeCompare(b.slug));
  return entries;
}

function render(entries) {
  const rows = entries
    .map((e) => {
      const glyphEsc = "\\u{" + e.hex + "}";
      return `  { name: ${JSON.stringify(e.name)}, slug: ${JSON.stringify(e.slug)}, hex: ${JSON.stringify(e.hex)}, glyph: "${glyphEsc}" },`;
    })
    .join("\n");
  return (
    "// GENERATED by scripts/build_icon_catalog.js from common/assets/icon_glyphs.yaml — do not edit by hand.\n" +
    "// The @mdi/font CDN version in index.html must track the bundled TTF (materialdesignicons-webfont-<ver>.ttf).\n\n" +
    "export interface IconEntry {\n" +
    "  name: string;\n" +
    "  slug: string;\n" +
    "  hex: string;\n" +
    "  glyph: string;\n" +
    "}\n\n" +
    "export const ICON_CATALOG: readonly IconEntry[] = [\n" +
    rows +
    "\n];\n\n" +
    "const BY_GLYPH: ReadonlyMap<string, IconEntry> = new Map(\n" +
    "  ICON_CATALOG.map((e) => [e.glyph, e]),\n" +
    ");\n" +
    "const BY_SLUG: ReadonlyMap<string, IconEntry> = new Map(\n" +
    "  ICON_CATALOG.map((e) => [e.slug, e]),\n" +
    ");\n\n" +
    "export function glyphToEntry(glyph: string): IconEntry | undefined {\n" +
    "  return BY_GLYPH.get(glyph);\n" +
    "}\n\n" +
    "// Resolve an MDI slug (e.g. \"lightbulb\") to its glyph, but only when the\n" +
    "// firmware actually bundles it — callers use this to keep to the renderable set.\n" +
    "export function slugToGlyph(slug: string): string | undefined {\n" +
    "  return BY_SLUG.get(slug)?.glyph;\n" +
    "}\n\n" +
    "export function filterIcons(query: string): readonly IconEntry[] {\n" +
    "  const q = query.trim().toLowerCase();\n" +
    "  if (q === \"\") return ICON_CATALOG;\n" +
    "  return ICON_CATALOG.filter((e) => e.slug.includes(q) || e.name.includes(q));\n" +
    "}\n"
  );
}

function main() {
  const check = process.argv.includes("--check");
  const entries = parseCatalog(fs.readFileSync(SRC, "utf-8"));
  if (entries.length === 0) throw new Error(`no glyphs parsed from ${SRC}`);
  const next = render(entries);
  if (check) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf-8") : "";
    if (current !== next) {
      console.error(`${OUT} is stale — run: node scripts/build_icon_catalog.js`);
      process.exit(1);
    }
    console.log(`icon_catalog.ts up to date (${entries.length} icons)`);
    return;
  }
  fs.writeFileSync(OUT, next);
  console.log(`wrote ${OUT}: ${entries.length} icons`);
}

module.exports = { parseCatalog, render };

if (require.main === module) main();
